apiVersion: v1
kind: Service
metadata:
  name: {{ template "promitor-scraper.fullname" . }}
  labels:
    app: {{ template "promitor-scraper.name" . }}
    chart: {{ template "promitor-scraper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: {{ .Values.service.labelType }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ template "promitor-scraper.name" . }}
    release: {{ .Release.Name }}
    type: {{ .Values.service.selectorType }}
