{{- if .Values.secrets.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "promitor-agent-resource-discovery.secretname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promitor-agent-resource-discovery.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.appKeySecret }}: {{ .Values.azureAuthentication.appKey | b64enc | quote }}
{{- end }}
