apiVersion: v1
kind: Service
metadata:
  name: {{ template "promitor-agent-resource-discovery.fullname" . }}
  labels:
    app: {{ template "promitor-agent-resource-discovery.name" . }}
    chart: {{ template "promitor-agent-resource-discovery.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: {{ .Values.service.labelType }}
spec:
{{- if .Values.service.exposeExternally }}
  type: LoadBalancer
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ template "promitor-agent-resource-discovery.name" . }}
    release: {{ .Release.Name }}
    type: {{ .Values.service.selectorType }}
