{{- if and .Values.rbac.create .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "promitor-agent-resource-discovery.serviceaccountname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promitor-agent-resource-discovery.labels" . | nindent 4 }}
  {{- if .Values.rbac.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.rbac.serviceAccount.annotations | nindent 4 }}
  {{- end }}
{{- end -}}
