apiVersion: v1
kind: Service
metadata:
  name: {{ template "promitor-agent-resource-discovery.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promitor-agent-resource-discovery.labels" . | nindent 4 }}
{{- if and (.Values.service.loadBalancer.enabled) (.Values.service.loadbalancer.azure.dnsPrefix) }}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Values.service.loadbalancer.azure.dnsPrefix }}
{{- end }}
spec:
{{- if .Values.service.loadBalancer.enabled }}
  type: LoadBalancer
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "promitor-agent-resource-discovery.selectorLabels" . | nindent 4 }}
