apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: promitor-scraper
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: promitor-scraper
        type: runtime
    spec:
      containers:
        - name: containo-orders-api
          image: tomkerkhove/promitor-scraper:0.2.0
          env:
          - name:  PROMITOR_AUTH_APPID
            # Provide the Azure AD App Id
            # See documentation for more information - https://promitor.io/configuration/#authentication-with-azure-monitor
            value: ""
          - name:  PROMITOR_AUTH_APPKEY
            valueFrom:
              secretKeyRef:
                name: promitor-scraper
                key: PROMITOR_AUTH_APPKEY
          volumeMounts:
          - name: promitor-scraper-metrics-config-volume
            mountPath: /config/
      volumes:
        - name: promitor-scraper-metrics-config-volume
          configMap:
            name: promitor-scraper-metrics-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promitor-scraper-metrics-config
data:
  # Provide your own version of the metric scraping declaration.
  # This version uses a sample.
  # See documentation for more information - https://promitor.io/configuration/metrics/
  metrics-declaration.yaml: |-
    azureMetadata:
      tenantId: c8819874-9e56-4e3f-b1a8-1c0325138f27
      subscriptionId: 0f9d7fea-99e8-4768-8672-06a28514f77e
      resourceGroupName: promitor
    metrics: 
        # v1.0
      - name: demo_queue_size
        description: "Amount of active messages of the 'myqueue' queue"
        resourceType: ServiceBusQueue
        namespace: promitor-messaging
        queueName: orders
        azureMetricConfiguration:
          metricName: ActiveMessages
          aggregation: Total
---
apiVersion: v1
kind: Service
metadata:
  name: promitor-scraper
  labels:
    app: promitor-scraper
    type: infrastructure
spec:
  type: LoadBalancer
  selector:
    app: promitor-scraper
    type: runtime
  ports:
  - protocol: TCP
    port: 1337
    targetPort: 80
---
apiVersion: v1
kind: Secret
metadata:
  name: promitor-scraper
type: Opaque
data:
  # Provide a base64 version of the key for your Azure AD App
  # See documentation for more information - https://promitor.io/configuration/#authentication-with-azure-monitor
  PROMITOR_AUTH_APPKEY: ProvideYourOwn
