version: '3.4'

services:
  promitor.scraper:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - PROMITOR_HTTP_PORT=88
      - PROMITOR_AUTH_APPID=ceb249a3-44ce-4c90-8863-6776336f5b7e
      - PROMITOR_AUTH_APPKEY=ZgLy6zYNh9SEmIl0B+rv+ZuQQ2wJyQi/tTXnp2Wp9PM=
      - PROMITOR_TELEMETRY_INSTRUMENTATIONKEY=
      - PROMITOR_LOGGING_MINIMUMLOGLEVEL=Trace
      - "SECRETS_STORAGEQUEUE_SAS=?sv=2018-03-28&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-07-28T02:33:14Z&st=2019-03-24T18:33:14Z&spr=https&sig=OiwNEYueCWlOhveapM1K6cRgV%2Be21gNhoq%2FDZqJEMZE%3D"
    ports:
      - "88"