azureMetadata:
  tenantId: c8819874-9e56-4e3f-b1a8-1c0325138f27
  subscriptionId: 0f9d7fea-99e8-4768-8672-06a28514f77e
  resourceGroupName: promitor
metricDefaults:
  aggregation:
    interval: 00:05:00
  scraping:
    # Every minute
    schedule: "0 * * ? * *"
metrics:
  - name: promitor_demo_generic_queue_size
    description: "Amount of active messages of the 'orders' queue (determined with Generic provider)"
    resourceType: Generic
    resourceUri: Microsoft.ServiceBus/namespaces/promitor-messaging
    filter: EntityName eq 'orders'
    labels:
      app: promitor
    azureMetricConfiguration:
      metricName: ActiveMessages
      aggregation:
        type: Average
  - name: promitor_demo_generic_namespace_size
    description: "Size of all queues in our Azure Service Bus namespace (determined with Generic provider)"
    resourceType: Generic
    resourceUri: Microsoft.ServiceBus/namespaces/promitor-messaging
    # filter is deliberately omitted given filter is optional
    scraping:
      # Every 2 minutes
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: ActiveMessages
      aggregation:
        type: Average
  - name: promitor_demo_servicebusqueue_queue_size
    description: "Amount of active messages of the 'orders' queue (determined with ServiceBusQueue provider)"
    resourceType: ServiceBusQueue
    namespace: promitor-messaging
    queueName: orders
    azureMetricConfiguration:
      metricName: ActiveMessages
      aggregation:
        type: Average
        # Optionally override the default aggregation interval (metricDefaults.aggregation.interval)
        interval: 00:15:00
  - name: promitor_demo_azurestoragequeue_queue_size
    description: "Approximate amount of messages in 'orders' queue (determined with StorageQueue provider)"
    resourceType: StorageQueue
    accountName: promitor
    queueName: orders
    sasToken:
      rawValue: "?sv=2018-03-28&ss=bfqt&srt=sco&sp=rwdlacup&se=2019-07-28T02:33:14Z&st=2019-03-24T18:33:14Z&spr=https&sig=OiwNEYueCWlOhveapM1K6cRgV%2Be21gNhoq%2FDZqJEMZE%3D"
    scraping:
      # Every 2 minutes
      schedule: "0 */2 * ? * *"
    azureMetricConfiguration:
      metricName: MessageCount
      aggregation:
        type: Total
  - name: promitor_demo_azurestoragequeue_queue_timespentinqueue
    description: "Approximate amount of time that the oldest message has been in 'orders' queue (determined with StorageQueue provider)"
    resourceType: StorageQueue
    accountName: promitor
    queueName: orders
    sasToken:
      environmentVariable: SECRETS_STORAGEQUEUE_SAS
    azureMetricConfiguration:
      metricName: TimeSpentInQueue
      aggregation:
        type: Total
