server:
  httpPort: 88
prometheus:
  metricUnavailableValue: NaN
  enableMetricTimestamps: true # true by default
  scrapeEndpoint:
    baseUriPath: /scrape
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: true
    verbosity: warning
  containerLogs:
    isEnabled: true
    verbosity: trace
  defaultVerbosity: trace