server:
  httpPort: 80
prometheus:
  scrapeEndpoint:
    baseUriPath: /scrape
metricsConfiguration:
  absolutePath: /config/metrics-declaration.yaml
telemetry:
  applicationInsights:
    instrumentationKey: ABC
    isEnabled: true
  containerLogs:
    isEnabled: true
    verbosity: trace
  defaultVerbosity: warning
featureFlags:
  disableMetricTimestamps: true # false by default