{{- if and .Values.rbac.create .Values.rbac.podSecurityPolicyEnabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ template "promitor-agent-scraper.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promitor-agent-scraper.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "promitor-agent-scraper.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "promitor-agent-scraper.serviceaccountname" . }}
{{- end -}}
