apiVersion: v1
kind: Service
metadata:
  name: {{ template "promitor-agent-scraper.fullname" . }}
  labels:
    app: {{ template "promitor-agent-scraper.name" . }}
    chart: {{ template "promitor-agent-scraper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    type: {{ .Values.service.labelType }}
{{- if .Values.prometheus.enableServiceDiscovery }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: {{ .Values.prometheus.scrapeEndpointPath | quote }}
    prometheus.io/port: {{ .Values.service.targetPort | quote }}
{{- end }}
spec:
{{- if .Values.service.exposeExternally }}
  type: LoadBalancer
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ template "promitor-agent-scraper.name" . }}
    release: {{ .Release.Name }}
    type: {{ .Values.service.selectorType }}
